FROM {{ experiment.base_image }}

ARG EXP_DIR=/experiment
ARG STORAGE_DIR={{ experiment.storage_dir }}

COPY {{ requirements_file }} ${EXP_DIR}/requirements.txt
RUN pip install --no-cache-dir -r $EXP_DIR/requirements.txt
{%- for path in experiment.paths_to_copy or ['.'] %}
COPY {{ path }} ${EXP_DIR}/{{ path }}
{%-  endfor %}
ENV STORAGE_DIR=${STORAGE_DIR}

VOLUME ${STORAGE_DIR}
VOLUME ${EXP_DIR}
WORKDIR ${EXP_DIR}

ENTRYPOINT ["{{ experiment.cmd_without_params|join('", "') }}"]
